#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.6
# from Racc grammer file "".
#

require 'racc/parser.rb'

  require "#{File.dirname __FILE__}/lexer"
  require "#{File.dirname __FILE__}/nodes"

module Carroll
  class Parser < Racc::Parser

module_eval(<<'...end grammar.y/module_eval...', 'grammar.y', 44)
  def parse code
    @tokens = Carroll::Lexer.new.tokenize code
    do_parse
  end

  def next_token
    @tokens.shift
  end
...end grammar.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    11,    13,     1,    21,    20,     3,     4,     1,     6,    19,
     3,     4,     1,     6,     2,     3,     4,     1,     6,     2,
     3,     4,    33,     6,     2,    27,    22,     1,    23,     2,
     3,     4,     1,     6,    30,     3,     4,    10,     6,     2,
    29,    32,     1,     9,     2,     3,     4,     1,     6,     8,
     3,     4,    28,     6,     2,    24,   nil,     1,   nil,     2,
     3,     4,     1,     6,   nil,     3,     4,   nil,     6,     2,
   nil,   nil,    35,   nil,     2,    15,    16,    17,   nil,   nil,
   nil,   nil,   nil,   nil,    14 ]

racc_action_check = [
     5,     6,     5,    11,    10,     5,     5,     0,     5,     9,
     0,     0,    31,     0,     5,    31,    31,    29,    31,     0,
    29,    29,    31,    29,    31,    23,    13,    32,    14,    29,
    32,    32,    26,    32,    27,    26,    26,     4,    26,    32,
    26,    30,    25,     2,    26,    25,    25,    22,    25,     1,
    22,    22,    25,    22,    25,    19,   nil,    20,   nil,    22,
    20,    20,    34,    20,   nil,    34,    34,   nil,    34,    20,
   nil,   nil,    34,   nil,    34,     8,     8,     8,   nil,   nil,
   nil,   nil,   nil,   nil,     8 ]

racc_action_pointer = [
     5,    36,    41,   nil,    35,     0,    -1,   nil,    73,     7,
    -3,     3,   nil,    17,    14,   nil,   nil,   nil,   nil,    40,
    55,   nil,    45,     9,   nil,    40,    30,    32,   nil,    15,
    26,    10,    25,   nil,    60,   nil ]

racc_action_default = [
   -12,   -12,   -12,    -3,   -12,   -12,   -12,    -1,   -12,   -12,
   -12,   -12,    -2,   -12,   -12,    -5,   -11,    -9,    -6,   -12,
   -12,    36,   -12,   -12,    -8,   -12,   -12,   -12,    -4,   -12,
   -12,   -12,   -12,    -7,   -12,   -10 ]

racc_goto_table = [
     5,    18,   nil,   nil,    12,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    25,   nil,    26,   nil,    12,    12,   nil,   nil,   nil,    31,
    12,   nil,    34,    12 ]

racc_goto_check = [
     1,     3,   nil,   nil,     2,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
     1,   nil,     1,   nil,     2,     2,   nil,   nil,   nil,     1,
     2,   nil,     1,     2 ]

racc_goto_pointer = [
   nil,     0,    -1,    -7 ]

racc_goto_default = [
   nil,   nil,     7,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 18, :_reduce_1,
  2, 18, :_reduce_2,
  1, 19, :_reduce_3,
  5, 19, :_reduce_4,
  3, 19, :_reduce_5,
  3, 19, :_reduce_6,
  7, 19, :_reduce_7,
  4, 19, :_reduce_8,
  1, 20, :_reduce_9,
  7, 20, :_reduce_10,
  1, 20, :_reduce_11 ]

racc_reduce_n = 12

racc_shift_n = 36

racc_token_table = {
  false => 0,
  :error => 1,
  :IDENTIFIER => 2,
  :LITERAL => 3,
  :NUMBER => 4,
  :SKIP => 5,
  :LOCAL => 6,
  :IN => 7,
  :IF => 8,
  :THEN => 9,
  :ELSE => 10,
  :PROC => 11,
  :END => 12,
  "=" => 13,
  "{" => 14,
  "}" => 15,
  "$" => 16 }

racc_nt_base = 17

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "IDENTIFIER",
  "LITERAL",
  "NUMBER",
  "SKIP",
  "LOCAL",
  "IN",
  "IF",
  "THEN",
  "ELSE",
  "PROC",
  "END",
  "\"=\"",
  "\"{\"",
  "\"}\"",
  "\"$\"",
  "$start",
  "Statements",
  "Statement",
  "Value" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'grammar.y', 18)
  def _reduce_1(val, _values, result)
     result = Node::AST.new val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 19)
  def _reduce_2(val, _values, result)
     result = val[0] << val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 23)
  def _reduce_3(val, _values, result)
     result = Node::Skip 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 24)
  def _reduce_4(val, _values, result)
     result = Node::Local.new val[1], val[3] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 25)
  def _reduce_5(val, _values, result)
     result = Node::UnifyVariable.new val[0], val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 26)
  def _reduce_6(val, _values, result)
     result = Node::UnifyValue.new val[0], val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 27)
  def _reduce_7(val, _values, result)
     result = Node::Conditional.new val[1], val[3], val[5] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 28)
  def _reduce_8(val, _values, result)
     result = Node::Application.new val[1], val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 32)
  def _reduce_9(val, _values, result)
     result = Node::Number.new val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 33)
  def _reduce_10(val, _values, result)
     result = Node::Procedure.new val[3], val[5] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 34)
  def _reduce_11(val, _values, result)
     result = Node::Literal.new val[0] 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module Carroll
