#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.6
# from Racc grammer file "".
#

require 'racc/parser.rb'

  require "#{File.dirname __FILE__}/lexer"
  require "#{File.dirname __FILE__}/nodes"

module Carroll
  class Parser < Racc::Parser

module_eval(<<'...end grammar.y/module_eval...', 'grammar.y', 59)
  def parse code
    @tokens = Carroll::Lexer.new.tokenize code
    do_parse
  end

  def next_token
    @tokens.shift
  end
...end grammar.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    13,    21,     2,    27,    27,     4,     5,    23,     6,     2,
    32,    33,     4,     5,     3,     6,    40,    28,    31,    42,
     2,     3,    26,     4,     5,     2,     6,    22,     4,     5,
     2,     6,     3,     4,     5,    45,     6,     3,    21,    24,
     2,    38,     3,     4,     5,    25,     6,     2,    36,    11,
     4,     5,     3,     6,    41,    10,     9,    35,     2,     3,
    44,     4,     5,     2,     6,     8,     4,     5,     2,     6,
     3,     4,     5,   nil,     6,     3,    16,    17,    19,   nil,
     3,   nil,   nil,   nil,   nil,    14 ]

racc_action_check = [
     7,    31,     7,    37,    20,     7,     7,    11,     7,    39,
    26,    26,    39,    39,     7,    39,    37,    20,    25,    39,
    40,    39,    17,    40,    40,    43,    40,    10,    43,    43,
    36,    43,    40,    36,    36,    43,    36,    43,     9,    13,
    30,    34,    36,    30,    30,    14,    30,    29,    30,     6,
    29,    29,    30,    29,    38,     5,     3,    29,    23,    29,
    41,    23,    23,     0,    23,     2,     0,     0,    22,     0,
    23,    22,    22,   nil,    22,     0,     8,     8,     8,   nil,
    22,   nil,   nil,   nil,   nil,     8 ]

racc_action_pointer = [
    61,   nil,    52,    54,   nil,    53,    47,     0,    74,    36,
    20,    -2,   nil,    39,    31,   nil,   nil,     5,   nil,   nil,
     2,   nil,    66,    56,   nil,     2,     7,   nil,   nil,    45,
    38,    -1,   nil,   nil,    23,   nil,    28,     1,    52,     7,
    18,    41,   nil,    23,   nil,   nil ]

racc_action_default = [
   -18,    -1,   -18,   -18,    -5,   -18,   -18,   -18,   -18,   -18,
   -18,   -18,    -2,   -18,   -18,    -8,    -7,   -14,   -13,   -11,
   -18,    -3,   -18,   -18,    46,   -18,   -18,    -4,   -10,   -18,
   -18,   -18,   -17,   -16,   -18,    -6,   -18,   -18,   -18,   -18,
   -18,   -18,    -9,   -18,   -15,   -12 ]

racc_goto_table = [
     7,    15,    12,    18,    20,    34,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    29,    30,    12,    12,    37,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    12,   nil,    39,   nil,    12,   nil,
    43 ]

racc_goto_check = [
     1,     4,     2,     5,     3,     6,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,     1,     1,     2,     2,     3,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,     2,   nil,     1,   nil,     2,   nil,
     1 ]

racc_goto_pointer = [
   nil,     0,    -5,    -5,    -7,    -5,   -21 ]

racc_goto_default = [
   nil,   nil,     1,   nil,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 21, :_reduce_1,
  2, 21, :_reduce_2,
  1, 23, :_reduce_3,
  2, 23, :_reduce_4,
  1, 22, :_reduce_5,
  5, 22, :_reduce_6,
  3, 22, :_reduce_7,
  3, 22, :_reduce_8,
  7, 22, :_reduce_9,
  4, 22, :_reduce_10,
  1, 24, :_reduce_11,
  7, 24, :_reduce_12,
  1, 24, :_reduce_13,
  1, 25, :_reduce_14,
  6, 25, :_reduce_15,
  1, 26, :_reduce_16,
  1, 26, :_reduce_17 ]

racc_reduce_n = 18

racc_shift_n = 46

racc_token_table = {
  false => 0,
  :error => 1,
  :IDENTIFIER => 2,
  :LITERAL => 3,
  :NUMBER => 4,
  :SKIP => 5,
  :LOCAL => 6,
  :IN => 7,
  :IF => 8,
  :THEN => 9,
  :ELSE => 10,
  :PROC => 11,
  :END => 12,
  "=" => 13,
  "{" => 14,
  "}" => 15,
  "$" => 16,
  "(" => 17,
  ":" => 18,
  ")" => 19 }

racc_nt_base = 20

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "IDENTIFIER",
  "LITERAL",
  "NUMBER",
  "SKIP",
  "LOCAL",
  "IN",
  "IF",
  "THEN",
  "ELSE",
  "PROC",
  "END",
  "\"=\"",
  "\"{\"",
  "\"}\"",
  "\"$\"",
  "\"(\"",
  "\":\"",
  "\")\"",
  "$start",
  "Statements",
  "Statement",
  "Identifiers",
  "Value",
  "Record",
  "Feature" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'grammar.y', 18)
  def _reduce_1(val, _values, result)
     result = Node::AST.new val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 19)
  def _reduce_2(val, _values, result)
     result = val[0] << val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 23)
  def _reduce_3(val, _values, result)
     result = Array.[] val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 24)
  def _reduce_4(val, _values, result)
     result = val[0] << val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 28)
  def _reduce_5(val, _values, result)
     result = Node::Skip 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 29)
  def _reduce_6(val, _values, result)
     result = Node::Local.new val[1], val[3] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 30)
  def _reduce_7(val, _values, result)
     result = Node::UnifyVariable.new val[0], val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 31)
  def _reduce_8(val, _values, result)
     result = Node::UnifyValue.new val[0], val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 32)
  def _reduce_9(val, _values, result)
     result = Node::Conditional.new val[1], val[3], val[5] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 33)
  def _reduce_10(val, _values, result)
     result = Node::Application.new val[1], val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 37)
  def _reduce_11(val, _values, result)
     result = Node::Number.new val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 38)
  def _reduce_12(val, _values, result)
     result = Node::Procedure.new val[3], val[5] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 39)
  def _reduce_13(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 43)
  def _reduce_14(val, _values, result)
     result = Node::Literal.new val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 44)
  def _reduce_15(val, _values, result)
     result = Node::Literal.new val[0], val[2], val[4] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 48)
  def _reduce_16(val, _values, result)
     result = Node::Number.new val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 49)
  def _reduce_17(val, _values, result)
     result = Node::Literal.new val[0] 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module Carroll
